### ISSUE TITLE
Descriptive errors

### ISSUE THREAD

**Issue by trajche** [rristov60/XBacnet#5]
Congrats on the first release!

Is it possible to add more descriptive errors?

Currently I receive errors like this, which are difficult to debug.

`An error occurred: Error: BacnetAbort - Reason:2!`

<img width="673" alt="image" src="https://user-images.githubusercontent.com/2382019/181005604-771ec68e-2efd-4f2f-a131-92eb0923e3bb.png">

**Comment by rristov60** [comment]
Thank you !

Thanks for pointing this out. Yes, it is possible to receive more verbose errors. This feature will be available in the next release.

In the meantime please resort to the following link https://docs.webfactory-i4.com/webfactory2010/en/bacnet-status-codes.html for detailed information about the status codes.

Hope this helps !

**Comment by rristov60** [comment]
Just a quick follow up, the new release v1.0.1 has descriptive errors implemented and it is available on https://xbacnet.com or directly from the releases
